apiVersion: v1
kind: ConfigMap
data:
  db-sync.sh: |-
    #!/bin/bash
    set -ex

    keystone-manage db_sync
    {% if network.ingress.enabled -%}
      kolla_keystone_bootstrap {{ admin_user }} {{ admin_password }} {{ admin_project_name }} admin http://keystone-api:{{ network.port.admin }}/v3 http://keystone-api:{{ network.port.public }}/v3 http://{{ network.ingress.named_host }}:{{ network.ingress.port }}/v3 {{ admin_region_name }}
    {%- else -%}
      kolla_keystone_bootstrap {{ admin_user }} {{ admin_password }} {{ admin_project_name }} admin http://keystone-api:{{ network.port.admin }}/v3 http://keystone-api:{{ network.port.public }}/v3 http://keystone-api:{{ network.port.public }}/v3 {{ admin_region_name }}
    {%- endif -%}
