apiVersion: v1
kind: ConfigMap
metadata:
  namespace: {{ namespace }}
  name: keystone-initsh
data:
  init.sh: |-
    #!/bin/bash
    set -ex

    ansible localhost -vvv -m mysql_db -a "login_host='{{ database_address }}' login_port='{{ database_port }}' login_user='{{ database_user }}' login_password='{{ database_password }}' name='{{ database_keystone_name }}'"
    ansible localhost -vvv -m mysql_user -a "login_host='{{ database_address }}' login_port='{{ database_port }}' login_user='{{ database_user }}' login_password='{{ database_password }}' name='{{ database_keystone_user }}' password='{{ database_keystone_password }}' host='%' priv='{{ database_keystone_name }}.*:ALL' append_privs='yes'"
