apiVersion: v1
kind: ConfigMap
data:
  rabbitmq.config: |-
    [
      {kernel, [
        {inet_dist_use_interface, { {{ network.ip_address_erlang }} }},
        {inet_dist_listen_min, {{ network.port.cluster }} },
        {inet_dist_listen_max, {{ network.port.cluster }} }
      ]},
      {rabbit, [
        {tcp_listeners, [
          { "{{ network.ip_address }}", {{ network.port.rabbitmq }} }
        ]},
        {default_user, <<"{{ admin_user }}">>},
        {default_pass, <<"{{ admin_password }}">>},
        {cluster_partition_handling, autoheal}
      ]},
      {rabbitmq_management, [
        {listener, [
          {ip, "{{ network.ip_address }}"},
          {port, {{ network.port.management }} }
        ]}
      ]},
      {rabbitmq_clusterer, [{config, "/etc/rabbitmq/rabbitmq-clusterer.config"}]}
    ].
    % EOF
