apiVersion: v1
kind: ConfigMap
data:
  rabbitmq-clusterer.config: |-
    [{version, 1},
     {nodes, [" {{ network.ip_address }}" ]},
     {gospel,
      {node, "rabbit@{{ network.ip_address }}" }
     }
     ].
