apiVersion: v1
kind: ConfigMap
data:
  start.sh: |-
    #!/bin/bash
    set -ex

    mkdir -p /var/lib/rabbitmq

    echo "{{ rabbitmq.erlang_cookie }}" > /var/lib/rabbitmq/.erlang.cookie
    chmod 400 /var/lib/rabbitmq/.erlang.cookie

    chown -R rabbitmq: /var/lib/rabbitmq

    mkdir -p /var/log/kolla/rabbitmq
    chmod 755 /var/log/kolla/rabbitmq

    rabbitmq-server
