apiVersion: v1
kind: ConfigMap
metadata:
  namespace: {{ variables.deployment.namespace }}
  name: keystone-dbsyncsh
data:
  db-sync.sh: |-
    #!/bin/bash
    set -ex

    glance-manage db_sync
    chown -R glance: /var/lib/glance/
