apiVersion: v1
kind: ConfigMap
metadata:
  namespace: {{ deployment.namespace }}
  name: glance-postsh
data:
  post.sh: |-
    #!/bin/bash
    set -ex

    ansible localhost -vvv -m kolla_keystone_service -a "service_name=glance service_type=image description='Openstack Image' endpoint_region={{ keystone.glance_region_name }} url='http://glance-api:{{ network.port.api }}' interface=admin region_name={{ keystone.admin_region_name }} auth='{{ keystone.auth }}'" -e "{ 'openstack_glance_auth': {{ keystone.auth }} }"
    ansible localhost -vvv -m kolla_keystone_service -a "service_name=glance service_type=image description='Openstack Image' endpoint_region={{ keystone.glance_region_name }} url='http://glance-api:{{ network.port.api }}' interface=internal region_name={{ keystone.admin_region_name }} auth='{{ keystone.auth }}'" -e "{ 'openstack_glance_auth': {{ keystone.auth }} }"
    ansible localhost -vvv -m kolla_keystone_service -a "service_name=glance service_type=image description='Openstack Image' endpoint_region={{ keystone.glance_region_name }} url='http://glance-api:{{ network.port.api }}' interface=public region_name={{ keystone.admin_region_name }} auth='{{ keystone.auth }}' " -e "{ 'openstack_glance_auth': {{ keystone.auth }} }"
    ansible localhost -vvv -m kolla_keystone_user -a "project=service user=glance password={{ keystone.glance_password }} role=admin region_name={{ keystone.admin_region_name }} auth='{{ keystone.auth }}'" -e "{'openstack_glance_auth':{{ keystone.auth }}}"

    ansible localhost -vvv -m mysql_db -a "login_host='{{ database.address }}' login_port='{{ database.port }}' login_user='{{ database.root_user }}' login_password='{{ database.root_password }}' name='{{ database.glance_database_name }}'"
    ansible localhost -vvv -m mysql_user -a "login_host='{{ database.address }}' login_port='{{ database.port }}' login_user='{{ database.root_user }}' login_password='{{ database.root_password }}' name='{{ database.glance_user }}' password='{{ database.glance_password }}' host='%' priv='{{ database.glance_database_name }}.*:ALL' append_privs='yes'"
