---

####################
# Ceph
####################
ceph_glance_pool_type: "{{ ceph_pool_type }}"
ceph_glance_cache_mode: "{{ ceph_cache_mode }}"

# Due to Ansible issues on include, you cannot override these variables. Please
# override the variables they refernce instead.
glance_pool_name: "{{ ceph_glance_pool_name }}"
glance_pool_type: "{{ ceph_glance_pool_type }}"
glance_cache_mode: "{{ ceph_glance_cache_mode }}"


####################
# Database
####################
glance_database_name: "glance"
glance_database_user: "glance"
glance_database_address: "{{ database_address }}"


####################
# Docker
####################
glance_registry_image: "{{ docker_registry ~ '/' if docker_registry else '' }}{{ docker_namespace }}/{{ kolla_base_distro }}-{{ kolla_install_type }}-glance-registry"
glance_registry_tag: "{{ openstack_release }}"
glance_registry_image_full: "{{ glance_registry_image }}:{{ glance_registry_tag }}"

glance_api_image: "{{ docker_registry ~ '/' if docker_registry else '' }}{{ docker_namespace }}/{{ kolla_base_distro }}-{{ kolla_install_type }}-glance-api"
glance_api_tag: "{{ openstack_release }}"
glance_api_image_full: "{{ glance_api_image }}:{{ glance_api_tag }}"


####################
# Openstack
####################
glance_admin_endpoint: "http://{{ glance_api_host }}:{{ glance_api_port }}"
glance_internal_endpoint: "http://{{ glance_api_host }}:{{ glance_api_port }}"
glance_public_endpoint: "http://{{ glance_api_host }}:{{ glance_api_port }}"

glance_logging_verbose: "{{ openstack_logging_verbose }}"
glance_logging_debug: "{{ openstack_logging_debug }}"

glance_keystone_user: "glance"

openstack_glance_auth: "{'auth_url':'{{ openstack_auth_url }}','username':'{{ openstack_username }}','password':'{{ openstack_password }}','project_name':'{{ openstack_project_name }}','domain_name':'default'}"

glance_registry_host: "glance-registry"

####################
# Resources
####################
# glance-api
glance_api_mem: "{{ glance_api_mem|default('128') }}"
glance_api_cpus: "{{ glance_api_cpus|default('0.3') }}"
# glance-init
glance_init_mem: "{{ glance_init_mem|default('512') }}"
glance_init_cpus: "{{ glance_init_cpus|default('0.3') }}"
# glance-registry
glance_registry_mem: "{{ glance_registry_mem|default('128') }}"
glance_registry_cpus: "{{ glance_registry_cpus|default('0.3') }}"
