apiVersion: v1
kind: ConfigMap
data:
  cinder.conf: |-
    [DEFAULT]
    debug = {{ misc.debug }}
    use_syslog = False
    use_stderr = True

    enable_v1_api=false
    volume_name_template = %s

    glance_api_servers = {{ glance_location }}
    glance_api_version = 2

    os_region_name = {{ keystone.cinder_region_name }}

    osapi_volume_workers = {{ misc.workers }}
    osapi_volume_listen = {{ network.ip_address }}
    osapi_volume_listen_port = {{ network.port }}

    default_volume_type = rbd-1
    enabled_backends = rbd-1

    api_paste_config = /etc/cinder/api-paste.ini
    nova_catalog_info = compute:nova:internalURL

    auth_strategy = keystone

    backup_driver = cinder.backup.drivers.ceph
    backup_ceph_conf = /etc/ceph/ceph.conf
    backup_ceph_user = {{ rados_gateway.cinder_backup_user }}
    backup_ceph_chunk_size = 134217728
    backup_ceph_pool = {{ rados_gateway.cinder_backup_pool }}
    backup_ceph_stripe_unit = 0
    backup_ceph_stripe_count = 0
    restore_discard_excess_bytes = true

    [database]
    connection = mysql+pymysql://{{ database.cinder_user }}:{{ database.cinder_password }}@{{ database.address }}/{{ database.cinder_database_name }}
    max_pool_size = {{ misc.workers }}
    max_overflow  = {{ misc.workers }}

    [keystone_authtoken]
    auth_uri = {{ keystone.auth_uri }}
    auth_url = {{ keystone.auth_url }}
    auth_type = password
    project_domain_id = default
    user_domain_id = default
    project_name = service
    username = {{ keystone.cinder_user }}
    password = {{ keystone.cinder_password }}

    [oslo_concurrency]
    lock_path = /var/lib/cinder/tmp

    [oslo_messaging_rabbit]
    rabbit_userid = {{ rabbitmq.admin_user }}
    rabbit_password = {{ rabbitmq.admin_password }}
    rabbit_ha_queues = true
    rabbit_hosts = {{ rabbitmq.address }}

    [rbd-1]
    volume_driver = cinder.volume.drivers.rbd.RBDDriver
    rbd_pool = {{ rados_gateway.cinder_pool }}
    rbd_ceph_conf = /etc/ceph/ceph.conf
    rbd_flatten_volume_from_snapshot = false
    rbd_max_clone_depth = 5
    rbd_store_chunk_size = 4
    rados_connect_timeout = -1
    rbd_user = {{ rados_gateway.cinder_user }}
    rbd_secret_uuid = {{ rados_gateway.secret_uuid }}
    report_discard_supported = True
