apiVersion: v1
kind: ConfigMap
data:
  libvirtd.conf: |-
    listen_tcp = 1
    auth_tcp = "none"
    ca_file = ""
    log_level = 2
    log_outputs = "2:stderr"
    listen_addr = "{{ network.ip_address }}"
