apiVersion: extensions/v1beta1
kind: Deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      nodeSelector:
        {{ deployment.node_label }}: enabled
      # TODO(DTadrzak): it must be removed in future
      securityContext:
        runAsUser: 0
      containers:
        - name: rabbitmq
          image: {{ deployment.image }}
          imagePullPolicy: Always
          # TODO(DTadrzak): it must be removed in future
          securityContext:
            privileged: true
          env:
            - name: INTERFACE_NAME
              value: "eth0"
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: COMMAND
              value: "bash /tmp/start.sh"
            - name: DEPENDENCY_CONFIG
              value: "/tmp/start.sh,/etc/rabbitmq/rabbitmq-env.conf,/etc/rabbitmq/rabbitmq.config,/etc/rabbitmq/rabbitmq-clusterer.config"
          ports:
            - containerPort: {{ network.port.rabbitmq }}
          readinessProbe:
            tcpSocket:
              port: {{ network.port.rabbitmq }}
          volumeMounts:
            - name: startsh
              mountPath: /configmaps/start.sh
            - name: rabbitmqenvconf
              mountPath: /configmaps/rabbitmq-env.conf
            - name: rabbitmqconfig
              mountPath: /configmaps/rabbitmq.config
            - name: rabbitmqclustererconfig
              mountPath: /configmaps/rabbitmq-clusterer.config
      volumes:
        - name: startsh
          configMap:
            name: rabbitmq-startsh
        - name: rabbitmqenvconf
          configMap:
            name: rabbitmq-rabbitmqenvconf
        - name: rabbitmqconfig
          configMap:
            name: rabbitmq-rabbitmqconfig
        - name: rabbitmqclustererconfig
          configMap:
            name: rabbitmq-rabbitmqclustererconfig
