apiVersion: v1
kind: ConfigMap
data:
  searchlight.conf: |-
    [DEFAULT]
    debug = {{ misc.debug }}
    log_file = searchlight.log
    # log_dir = /var/log/searchlight/

    use_syslog = False
    use_stderr = True

    transport_url = rabbit://{{ rabbitmq.admin_user }}:{{ rabbitmq.admin_password }}@{{ rabbitmq.address }}/

    [api]
    bind_port = {{ network.port.api }}
    workers = {{ misc.workers }}

    [elasticsearch]
    hosts = {{ elasticsearch.address }}

    [listener]
    workers = {{ misc.workers }}

    [oslo_messaging_notifications]
    driver = messaging
    transport_url = rabbit://{{ rabbitmq.admin_user }}:{{ rabbitmq.admin_password }}@{{ rabbitmq.address }}/
    topics = notifications

    [paste_deploy]
    flavor = keystone

    [keystone_authtoken]
    auth_uri = {{ keystone.auth_uri }}
    auth_url = {{ keystone.auth_url }}
    auth_type = password
    project_domain_id = default
    user_domain_id = default
    project_name = service
    username = {{ keystone.searchlight_user }}
    password = {{ keystone.searchlight_password }}

    [resource_plugin]
    enabled = false

    [resource_plugin:os_nova_server]
    enabled = true

    [service_credentials]
    auth_plugin = password
    auth_uri = {{ keystone.auth_uri }}
    auth_url = {{ keystone.auth_url }}
    username = {{ keystone.searchlight_user }}
    password = {{ keystone.searchlight_password }}
    tenant_name = service
