apiVersion: v1
kind: ConfigMap
data:
  my.cnf: |-
    [mysqld]
    bind-address={{ network.ip_address }}
    port={{ network.port.mariadb }}

    binlog_format=ROW
    default-storage-engine=innodb
    innodb_autoinc_lock_mode=2

    datadir=/var/lib/mysql/

    wsrep_cluster_address=gcomm://
    wsrep_provider_options="gmcast.listen_addr=tcp://{{ network.ip_address }}:{{ network.port.wsrep }};ist.recv_addr={{ network.ip_address }}:{{ network.port.ist }}"

    #wsrep_node_address={{ network.ip_address }}:{{ network.port.wsrep }}
    #wsrep_sst_receive_address={{ network.ip_address }}:{{ network.port.sst }}

    wsrep_provider=/usr/lib/galera/libgalera_smm.so
    wsrep_cluster_name="{{ database.cluster_name }}"
    wsrep_node_name={{ database.node_name }}
    wsrep_sst_method=xtrabackup-v2
    wsrep_sst_auth=root:{{ database.root_password }}
    wsrep_slave_threads=4

    max_connections=1000

    [server]
    pid-file=/var/lib/mysql/mariadb.pid
