apiVersion: v1
kind: ConfigMap
metadata:
  namespace: {{ variables.deployment.namespace }}
  name: mariadb-startsh
data:
  start.sh: |-
    #!/bin/bash
    set -ex

    # Setup folders and permissions.
    chown mysql: /var/lib/mysql

    mkdir -p /var/log/kolla/mariadb
    chmod 755 /var/log/kolla/mariadb

    # Initialize system database.
    su -s /bin/bash mysql - mysql -c 'mysql_install_db'

    # Start mariadb and wait for it to be ready.
    su -s /bin/bash mysql -c "mysqld_safe --wsrep-new-cluster &"

    TIMEOUT=120
    while [[ ! -f /var/lib/mysql/mariadb.pid ]]; do
    if [[ ${TIMEOUT} -gt 0 ]]; then
        let TIMEOUT-=1
        sleep 1
    else
        exit 1
    fi
    done

    # Reset permissions.
    DB_ROOT_PASSWORD="{{ variables.root_password }}" kolla_security_reset
    mysql -u root --password="{{ variables.root_password }}" -e "GRANT ALL PRIVILEGES ON *.* TO 'root'@'localhost' IDENTIFIED BY '{{ variables.root_password }}' WITH GRANT OPTION;"
    mysql -u root --password="{{ variables.root_password }}" -e "GRANT ALL PRIVILEGES ON *.* TO 'root'@'%' IDENTIFIED BY '{{ variables.root_password }}' WITH GRANT OPTION;"

    # Restart database.
    mysqladmin -uroot -p"{{ variables.root_password }}" shutdown
    su -s /bin/bash mysql -c "mysqld_safe --wsrep-new-cluster"
